# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-EU"
title                    : "Francisco Vergara"
email                    : fvergara.sand@gmail.com

title_separator          : "|"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Francisco Vergara"
description              : "Blogging about my transition into Data Engineering, I explain data engineer concepts using diagrams, animations and intuition + Minimal Mistakes Jekyll personal website"
twitter_username         : Sirfranvergara
github_username          : franvergara66
port                     : 4000
host                     : "0.0.0.0"
url                      : https://www.franvergara66.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
# teaser                   : /assets/images/joel-filipe-thumb-800.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : " " # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
read_time                : true
    


comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
repository: "franvergara66/blog-comments"



comments:
  provider               : utterances #"disqus" #false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    repository: "franvergara66/blog-comments"
#  disqus:
#    shortname            : cross-validated # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : #https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 # , e.g.: meta.discourse.org
  facebook               : #https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : #['name', 'email', 'url', 'message']
  branch                 : #"master"
  commitMessage          : #"New comment by {fields.name}"
  filename               : #comment-{@timestamp}
  format                 : #"yaml"
  moderation             : #true
  path                   : #"/_data/comments/{options.slug}"
  requiredFields         : #['name', 'email', 'message']
  transforms:
    email                : #"md5"
  generatedFields:
    date:
      type               : #"date"
      options:
        format           : #"iso8601" default, "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : 
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "sirfranvergara"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/logo-v4.jpg # Open Graph/Twitter default site image
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
# analytics:
#   provider               : google-gtag # false (default), "google", "google-universal", "custom"
#   google:
#     tracking_id          : UA-147237792-1
#     anonymize_ip         : false # false (default)
#     optimize_id          : GTM-WV93XGT
#     allow_google_signals : false


# Site Author
author:
  name   : "Francisco Vergara"
  avatar : "assets/images/profile.jpg"
  bio    : Computer Scientist - Data Engineer/Scientist
           Kick-butt Developer
           RESTafarian
           Animal Lover
  location: "Stuttgart, Germany"
  links:
    - label: "Stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/59468/franvergara66"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/franvergara66"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fvergara-sand/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sirfranvergara"
 
  
    - label: "Subscribe"
      icon: "fas fa-fw fa-envelope"
      url: "https://www.getrevue.co/profile/sirfranvergara"
    - label: "Support"
      icon: "fas fa-fw fa-mug-hot"
      url: "https://www.getrevue.co/profile/sirfranvergara"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Germany # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-sitemap
#  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap



tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
      mathjax: true
      read_time: true
      words_per_minute: 200

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

picture:
  source: "assets/images" #"assets/images/_originals"
  output: "assets/images"
  markup: "picture"
  presets:
    hero:
      attr:
        class: "page__hero-image"
        itemprop: "image"
      ppi: [1]
      source_1600:
        media: "(min-width: 1600px)"
        width: "1600"
      source_1024:
        media: "(min-width: 1024px)"
        width: "1024"
      source_768:
        media: "(min-width: 768px)"
        width: "768"
      source_600:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"
